- .gitignore
- package.json
Hi, 
First of all, thanks for the project! I'm currently using it for Mac App Store app and really saves my time.
I found that standard fails because of JavaScript files inside `test/work` directory, so this pull request adds ignore add settings to ignore `test/work` from standard and also Git.
> Ignore test/work directory from git and standard

- .travis.yml
- package.json
If you run [`npm test` in Travis](https://travis-ci.org/electron-userland/electron-osx-sign/jobs/113849722#L200-L201), you get this message:
```
Test failed.
Command failed: /bin/sh -c which codesign
```
Oddly enough, it doesn't fail (even though it should). This PR just runs `standard` so contributors don't get confused by the Travis output.
Let me know if there's a more idiomatic Node way of doing this.
References #18.
> Travis: only run standard, not tape

- README.md
- bin/electron-osx-flat-usage.txt
- bin/electron-osx-sign-usage.txt
- index.d.ts
- index.js
[electron-builder](https://github.com/electron-userland/electron-builder) now uses electron-osx-sign to sign app and MAS build.
Currently, I use my fork. Want to integrate my changes.
* use `execFile` instead of `exec` — no need to escape args.
* add  `keychain` option.
* remove code duplication — base args to `codesign` (so, the only place where add new `keychain` arg).
Also, I added TS definition file according to http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html
Why  `keychain` is required? Because electron-builder is a complete solution and supports code signing on a CI servers.
> Add keychain option

- index.js
Signed entitlements could not be ”verified” by codesign
> Debug log entitlements

- index.js
This resolves an issue with app not signed at all when immediately verify after last codesign command. Better solutions are welcome.
> Delay before codesign verify

- index.d.ts
- index.js
Otherwise if platform `darwin` no entitlements by default and sign failed because `preAutoEntitlementAppGroupAsync` does `readFileAsync(opts.entitlements, 'utf8')`
> Automating entitlement app group only if there is entitlements

- README.md
- bin/electron-osx-sign-usage.txt
- index.js
Add possibility to give the criteria that user recommends to be used to evaluate the code signature.
> Add requirements option

- README.md
- bin/electron-osx-sign-usage.txt
- index.js
:wave:
I wasn’t sure what the current status of the 0.4 rewrite was, but we need the `requirements` option so I figured I’d backport this in case there was any interest in creating a 0.3.2.
Backports https://github.com/electron-userland/electron-osx-sign/pull/68 on top of 0.3.1
> Backport requirements option

- bin/electron-osx-flat-usage.txt
- index.js
Added an option to accept 'scripts' as a parameter. Scripts is used by productBuild to accept pre and/or post install scripts.
> Added 'scripts' as an optional paramter

- sign.js
- util-provisioning-profiles.js
Development:
- Mac App Development
Create a provisioning profile to install development apps on test
devices.
Distribution:
- Developer ID
Create a Developer ID provisioning profile to use Apple services with
your Developer ID signed applications.
- Mac App Store
Create a distribution provisioning profile to submit your app to the
Mac App Store.
Refer to: https://developer.apple.com/account/mac/profile/create
> Allow platform/type specific provisioning profiles

- README.md
- bin/electron-osx-sign-usage.txt
- bin/electron-osx-sign.js
- index.d.ts
- sign.js
> Allow skipping Gatekeper check

- .gitignore
- .travis.yml
- package.json
- sign.js
- util.js
plist updated to 2.0 — it is safe to do major upgrade
> reject promise using Error and include error message

- README.md
- flat.js
- sign.js
- util-entitlements.js
- util-identities.js
- util-provisioning-profiles.js
- util.js
- Patches for release 0.4.2
- Fix #109 and overall code consistency
> Pre release 0.4.2 changes

- sign.js
Avoid the empty string argument in the `code sign --verify` if Darwin version is lower than 15.0 as explained in #117
> Fix #117: codesign --verify fails with "no such file or directory"

- index.d.ts
- package.json
- sign.js
Not documented because intended to be internal option for programmatic usage
> feat: skipIdentityValidation

- README.md
- test/basic.js
Modules like `electron-builder` have supported `pkg` output for app building. `electron-osx-flat` will no longer be maintained but still available for backward compatibility.
Addresses: https://github.com/electron-userland/electron-osx-sign/issues/96#issuecomment-285914180
> Deprecate electron-osx-flat

- util-identities.js
For issue #132,
Add `--use-cert-id` option to use the cert id instead of cert name
> Add use-cert-id option

- README.md
- bin/electron-osx-sign-usage.txt
- sign.js
For issue #132 ,
Add `--timestamp-none` option to use `--timestamp=none` when running `codesign`
> Add timestamp option

- README.md
- bin/electron-osx-flat-usage.txt
- bin/electron-osx-sign-usage.txt
- flat.js
- sign.js
- util-entitlements.js
- util-identities.js
> Use Identity instance containing name and hash

- README.md
- bin/electron-osx-sign-usage.txt
- sign.js
> Allow array of ignore options

- package.json
- util-entitlements.js
Reduce node_modules size — use the same approach to generate temp file as electron-builder/electron-download
> Remove tempfile dependency

- util-entitlements.js
-A false positive occurs when a string is set as the value for com.apple.security.application-groups in entitlements.
-Originally the check looked for the absence of app identifier in an array, which returned true even if the input is a string.
-This fixes that by ensuring the value is an array before searching for app identifier.
> Setting entitlements fails when app group value is a string

- sign.js
`codesign`'s `--timestamp` takes an optional value.
Fixes #163
> Fix timestamp option

- sign.js
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution requires the following,
> Include a secure timestamp with your code-signing signature. (The Xcode distribution workflow includes a secure timestamp by default. For custom workflows, include the --timestamp option when running the codesign tool.)
> Default to contact timestamp authority server

- README.md
- bin/electron-osx-sign-usage.txt
- bin/electron-osx-sign.js
- index.d.ts
- sign.js
> feat: adding signature-size option

- .npmignore
This PR will prevent npm from publishing the test files, the yarn lock file and the CircleCI config file.
> fix: Don't publish test files

- util-provisioning-profiles.js
Fixes (#206) - When the command `security cms` runs, it will default to system keychains during a bamboo build even if a keychain is passed in using the CSC_KEYCHAIN environment variable.
Inside of getProvisioningProfileAsync function (found within electron-osx-sign package) I added a keychain arg to surface the CSC_KEYCHAIN environment variable as a flag to the `security` command.
This is best reproduced on a bamboo build agent machine. If you do not have a bamboo server to test with, follow these instructions:
1) Toggle debug mode for electron osx sign `debug=electron-osx-sign` 
2) set `CSC_KEYCHAIN` environment variable
3) build and ensure that during the signing process that the correct keychain file is being used (instead of login or system keychain)
1) This is my first contribution …
> feat: added keychain arg to GetProvisioningProfileAsync

- index.d.ts
This adds a TypeScript type for the optional `hardenedRuntime` option.
(Ran into this in https://github.com/desktop/desktop/pull/8555)
> fix: add ts type for hardenedRuntime option

- util.js
In the current implementation, files with names like `.node` (`.node` as the base name, not as a file extension) will be skipped while scanning the application bundle. Testing all possible binary files should help clear the naming ambiguity. Files like `.gitignore` should still be skipped.
Addresses: #168
cc: @malept
> feat: Codesign all binary-like files

- sign.js
Well this is silly, but hey, 🤷‍♂️ 
Fixes https://github.com/electron/electron/issues/23534
> fix: sign child paths in order of depth

- README.md
- bin/electron-osx-sign-usage.txt
- index.d.ts
- sign.js
When signing the electron app for App Store, the Login Helper is signed child inherited entitlements. Since the Login Helper is a standalone executable, it crashes on because it shouldn't have the `com.apple.security.inherit`.
This PR adds an option to specify a custom entitlement file for the login helper.
> feat: Add option to specify login helper entitlements file

- .circleci/config.yml
Two things here:
1. The build is failing because `Job was rejected because resource class medium, image xcode:11.6.0 is not a valid resource class`. This image was removed from the platform earlier this year: https://discuss.circleci.com/t/xcode-image-deprecation/44294
2. Node 18 is hitting LTS in 2 weeks. This adds a Node 18 CI job and removes the Node 12 one as that versions is slated for deprecation.
> ci: update xcode and node versions

- .circleci/config.yml
- .github/workflows/semantic.yml
* Uses `continuousauth/npm` orb for CFA releases
* Uses `electronjs/node` orb to simplify config
* Adds Node.js v20 to the test matrix
* Bumps Xcode version to one not deprecated by CircleCI
* Enforces semantic commit messages so CFA releases work as expected
> build: do CFA releases

- src/index.ts
Hello,
I want to be able to import this type since I am calling some of the functions in this package.
I think this makes sense, especially since the sister-package `@electron/notarize` exports the `NotarizeOptions` type. https://github.com/electron/notarize/blob/11fcb0bc8ccb02a47c0a221f677b457f14d58fbf/src/index.ts
> fix: export `SignOptions` type

- src/sign.ts
Fixes https://github.com/electron/osx-sign/issues/291
Fixes https://github.com/electron-userland/electron-builder/issues/7653
I've tested this in production and managed to publish my app to Mac App Store with the changes.
CC: @MarshallOfSound @mmaietta
> fix: only apply `preAutoEntitlements` to top-level app bundle

- src/index.ts
- src/types.ts
This change exports the `walkAsync` function so that implementers can reliably generate an identical file list for purposes other than signing such as removing or inspecting individual file signatures. Also corrects type definition comments around requirements.
> feat: Exporting walkAsync

- README.md
- src/sign.ts
- src/types.ts
Adds docs, example and impl for using `--deep` in the "right" way.
Fixes #240
> feat: add support for and document --deep for subresources

- src/flat.ts
The `--scripts` should go to `pkgbuild` in order for preinstall and postinstall script to work. So the single `productbuild` command has to be separated into `pkgbuild` and `productbuild`.
I am not sure if the `--scripts` in `productbuild` has any practical use. Might need to add an new option if need to retain the `--scripts` for both `productbuild` and `pkgbuild`
> fix(flat): use `pkgbuild` to bundle pre/postinstall scripts

- README.md
Looks like this slipped by #337 when we moved over the configs from `electron/symbolicate-mac`.
> docs: fix GHA links

- src/flat.ts
- src/types.ts
Fixes #327
Fixes #328 
Fixes https://github.com/electron/forge/issues/3782
The `flat` function of `@electron/osx-sign` is used to generate `.pkg` archives for macOS. These archives can be installed on users' machines in two ways:
* via OS X Installer (i.e. clicking the `.pkg` archive on your file system)
* via the Mac App Store (MAS)
There are two underlying macOS tools that can be used to generate these archives: [`productbuild`](https://www.unix.com/man-page/osx/1/productbuild/) and [`pkgbuild`](https://www.unix.com/man-page/osx/1/pkgbuild/).
#282 fixed the problem of not being to use pre/postinstall scripts in `.pkg` installers by adding an additional `pkgbuild` incantation to add those scripts and inserting that build into the final `productbuild` bundle.
It turns out that this …
> fix(flat): don't use `pkgbuild` for MAS distributions

- src/sign.ts
- src/types.ts
And extend it to support string-specified restrictions
Fixes https://github.com/electron/osx-sign/issues/344
> fix: strictVerify not working with true value

- src/flat.ts
- src/sign.ts
- tsconfig.json
Fast follow-up to https://github.com/electron/osx-sign/pull/348
In the previous PR, I used `resolveJsonModule` to avoid a `@typescript-eslint/no-var-requires` error, but this led to the `dist` structure to change, which broke the tests.
> build: publish to correct directories again

- package.json
- src/sign.ts
- src/util-entitlements.ts
- src/util-provisioning-profiles.ts
- src/util.ts
- yarn.lock
As per internal maintainer discussion, the value from `graceful-fs` comes from its handling of filesystem errors on Windows.
Since this package is strictly for macOS code-signing, let's drop it as a dep and use `node:fs` directly.
> refactor: remove `graceful-fs`

- src/sign.ts
- src/types.ts
This adds the `batchCodesignCalls` option to allow signing all files with identical options at a given filesystem depth in a single `codesign` call (as opposed to running `codesign` once for each file in a serial fashion), which minimizes the number of child processes that need to be spawned and reduces the time it takes to sign the app. That option defaults to **`false`**, so users need to explicitly opt into that behavior.
---
I was recently debugging a code-signing issue and noticed in the logs that we're signing one file at a time, which translates to a few hundreds of `childProcess.exec('codesign')` calls. `codesign` supports passing multiple files at once, so we can take advantage of that to keep the number of child processes we have to spawn (and the associated overhead) to a …
> feat(perf): add `batchCodesignCalls` option to allow signing multiple files at once

- bin/electron-osx-flat.mjs
- package.json
- spec/cpio.spec.ts
- src/flat.ts
- src/pkg-utils/bom.ts
- src/pkg-utils/cpio.ts
- src/types.ts
A common problem with Electron apps is that when enterprises go to install them on their users machines they are installed as `755` which results in a application which can't be updated by every administrator. This results in Squirrel.Mac popping up permission prompts and other annoying things.
This somewhat arcane sequence of stuff modifies two things in the `pkg` file as it's being built:
* The BOM file that macOS uses to identify files in a PKG, this stores uid/gid/perms
* The ODC format gzipp'ed payload that contains the raw files the PKG will install (which also include uid/gid/perms)
We modify every instance of 755 to 775 and every instance of 644 to 664, and each file we modify becomes owned by `0:80` instead of `0:0` (root:admin)
A trillion tests because the somewhat arcane CPIO …
> feat: add option to set permissions for Foo.app to be squirrel.mac compatible
