README.md
bin/electron-osx-sign-usage.txt
bin/electron-osx-sign.js
index.js

This is a PR in response to #6.

Signing with additional binaries included

---

README.md
bin/electron-osx-flat-usage.txt
bin/electron-osx-flat.js
index.js
package.json
test/basic.js

This PR is a follow-up for #5 in extension to `productbuild`.

Flattening signed application package

---

index.js

Fix https://github.com/electron-userland/electron-osx-sign/issues/27

Use indexOf rather than includes

---

README.md
bin/electron-osx-sign-usage.txt
index.js

Fix https://github.com/electron-userland/electron-osx-sign/issues/30

opts.ignore to filter out undesired file paths for signing

---

index.js

Fix https://github.com/electron-userland/electron-osx-sign/issues/37

Fix darwin default entitlements

---

index.js

Remove verbose flag from code signing 
Also now use unambiguous force flag
Fixes #42

Post verify codesign

---

index.js

Fix opts.ignore validation logic

---

package.json

Fix test run

---

index.js

opts.ignored revised

---

.travis.yml
README.md
bin/electron-osx-sign-usage.txt
index.js

Validate sign by gatekeeper

---

README.md

Mention macOS working capability

---

sign.js

Addresses part of https://github.com/electron-userland/electron-osx-sign/issues/99.

Fix provisioning profile option validation

---

sign.js

Fixes #103
Issue regarding #91
---
Another article from last year that I read just now: http://furbo.org/2015/07/23/code-signing-in-el-capitan/

Only pass strict flag in El Capitan and later

---

README.md
bin/electron-osx-sign-usage.txt
index.d.ts

Fixes: https://github.com/electron-userland/electron-osx-sign/issues/104

Update TypeScript addressing recent updates

---

flat.js
sign.js

Display electron-osx-sign@version before running

---

sign.js

pre-embed-previsioning-profile => pre-embed-provisioning-profile

fix: debug log spelling mistake

---

README.md
bin/electron-osx-sign-usage.txt
bin/electron-osx-sign.js
sign.js

adding the ability to pass in restrict flag

feat: enable restrict mode

---

README.md

Following #202's switch to CircleCI

chore: Replace with CircleCI badge

---

.gitignore
README.md

Following #202, document a quick workaround for running tests locally.

chore: Update test doc

---

README.md
bin/electron-osx-sign-usage.txt
bin/electron-osx-sign.js
sign.js

adding the ability to passing in all code signature flags as comma-separated string and print warning for deprecating the restrict flag (it is one of the code signature flags)

feat: adding signature-flags to allow code signature flags

---

.releaserc.json
package.json
yarn.lock

I botched #287 and was missing a couple requirements for CFA.

build: add missing config for CFA releases

---

README.md

We renamed the package and repo.

docs: update Electron Packager reference

---

entitlements/default.darwin.plist

fix: add personal-information.photos-library entitlement in default.darwin.plist
